"""A business question: the specification, the acceptance test and what a page renders.

It is a data file rather than code, which is what keeps the vocabulary of one business out
of the machinery that runs it. The runner discovers questions and asserts over them; it
names nothing. ADR 0005.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Any

import duckdb
import yaml

FRONT_MATTER = re.compile(r"\A---\n(.*?)\n---\n(.*)\Z", re.DOTALL)
TOKEN = re.compile(r"\{\{([^}]+)\}\}")

STAGED = "staged.sql"
USS = "uss.sql"

# The prefix every bridge measure column carries, as a literal beside the layer names
# below. Generated by adss.uss; a test asserts the two still agree, which is the coupling
# without the import -- a question is a data file and does not depend on a generator.
MEASURE = "_measure__"


ID = re.compile(r"\A[a-z0-9][a-z0-9_-]*\Z")


class QuestionError(Exception):
    """A question that cannot be answered as written."""


class Status(StrEnum):
    DRAFT = "draft"
    RED = "red"
    GREEN = "green"
    SUPERSEDED = "superseded"


@dataclass(frozen=True, slots=True)
class Question:
    directory: Path
    id: str
    status: Status
    persona: str
    question: str
    dimensions: tuple[str, ...]
    defines: tuple[str, ...]
    staged_sql: str
    uss_sql: str
    body: str

    @property
    def tokens(self) -> tuple[str, ...]:
        return tuple(str(match).strip() for match in TOKEN.findall(self.body))


def without_comments(sql: str) -> str:
    """The SQL, without its commentary. A comment explaining a rule does not break it."""
    return "\n".join(line for line in sql.splitlines() if not line.lstrip().startswith("--"))


def _parsed(sql: str) -> dict[str, Any]:
    """The engine's own parse tree for this SQL, as plain data.

    Parsed rather than matched. An aggregate can be spelled over three lines, wrapped in a
    cast, or written as a window, and a regular expression that survived all three would still
    be reading string literals and comments as code.
    """
    tree: dict[str, Any] = {"error": True, "error_message": "the engine returned nothing"}
    connection = duckdb.connect(":memory:")
    try:
        found = connection.execute("SELECT json_serialize_sql(?)", [sql]).fetchone()
        if found:
            tree = json.loads(str(found[0]))
    finally:
        connection.close()
    return tree


def _aggregate_names() -> frozenset[str]:
    """Every aggregate the engine has, from the engine. A list kept by hand here would be
    wrong the first time somebody wrote `product` or `arg_max` instead of `sum`."""
    connection = duckdb.connect(":memory:")
    try:
        rows = connection.execute(
            "SELECT DISTINCT function_name FROM duckdb_functions() WHERE function_type = ?",
            ["aggregate"],
        ).fetchall()
    finally:
        connection.close()
    return frozenset(str(name).lower() for (name,) in rows)


def _children(node: object) -> list[object]:
    if isinstance(node, dict):
        return list(node.values())
    if isinstance(node, list):
        return list(node)
    return []


def _columns_under(node: object) -> list[str]:
    """Every column named anywhere below this node, qualifier and all.

    Walked with a stack rather than by recursion. The depth of this tree is the engine's
    business, not ours -- it accepts a thousand nested calls, which is twice what CPython will
    follow -- and a RecursionError coming out of a question checker is a refusal nobody can
    read.
    """
    found: list[str] = []
    pending: list[object] = [node]
    while pending:
        current = pending.pop()
        if isinstance(current, dict) and current.get("class") == "COLUMN_REF":
            names = current.get("column_names")
            parts = names if isinstance(names, list) else []
            found.append(".".join(str(part) for part in parts))
            continue
        pending += _children(current)
    return found


def protected(column: str) -> bool:
    """Whether the bridge protects this column reference. Named so a test can reach it.

    Only the LAST part of the reference decides, because what the bridge protects is a column.
    Testing the whole dotted name let a table aliased `_measure__x` launder its own attributes
    through the refusal -- an alias is the one part of a reference an author picks freely.

    A column aliased to a `_measure__` name inside a subquery still gets through, and closing
    that means resolving aliases rather than reading names. ADR 0012 records it.
    """
    return column.rpartition(".")[2].startswith(MEASURE)


def aggregated(
    tree: dict[str, Any], aggregates: frozenset[str]
) -> list[tuple[str, tuple[str, ...]]]:
    """Every aggregate in this parse tree, with the columns it is applied to.

    A windowed aggregate counts: `sum(x) OVER ()` multiplies exactly as a grouped sum does.
    An aggregate with no columns at all -- `count(*)` -- comes back with none, which is a
    different refusal rather than an absent one.
    """
    found: list[tuple[str, tuple[str, ...]]] = []
    pending: list[object] = [tree.get("statements")]
    while pending:
        current = pending.pop()
        if isinstance(current, dict):
            name = str(current.get("function_name", "")).lower()
            # A WINDOW node is an aggregate only when the engine says WINDOW_AGGREGATE.
            # `row_number`, `rank`, `ntile` and `lag` are all in duckdb_functions()'s aggregate
            # list, so reading that list alone refused "rank the months" -- an ordinary shape --
            # and sent its author looking for a fan-out that is not there.
            call = (
                current.get("type") == "WINDOW_AGGREGATE"
                if current.get("class") == "WINDOW"
                else current.get("class") == "FUNCTION" and not current.get("is_operator")
            )
            if call and name in aggregates:
                found.append((name, tuple(_columns_under(current.get("children", [])))))
        pending += _children(current)
    return found


def _refuse_an_aggregate_the_bridge_does_not_protect(
    question: Question, tree: dict[str, Any]
) -> None:
    """An answer query aggregates measures and nothing else. ADR 0012.

    The bridge protects a measure column with a typed null on every branch that does not own
    it. It protects nothing on a peripheral, and a numeric attribute that is also a measure's
    source is published in both places -- so one join and one sum returns a multiple of the
    truth, looking exactly like an answer.

    Stricter than the trap strictly requires: `count(DISTINCT p.thing)` cannot be multiplied
    by a fan-out, and is refused here anyway. The decision is that an answer aggregates
    measures, and narrowing it to the aggregates that can actually be wrong would be a rule
    nobody could apply without knowing which those are.
    """
    for name, columns in aggregated(tree, _aggregate_names()):
        if not columns:
            raise QuestionError(
                f"{question.id}: the answer query says {name}() over no column, which counts "
                f"measurement events rather than the thing anybody asked about -- two events "
                f"on one entity and it doubles. Sum the measure that counts them instead."
            )
        loose = [column for column in columns if not protected(column)]
        if loose:
            raise QuestionError(
                f"{question.id}: the answer query applies {name}() to {loose}, which the "
                f"bridge does not protect. A numeric attribute on a peripheral is published "
                f"beside the measure made from it and multiplies once per row of the finer "
                f"stage. Aggregate the {MEASURE} column instead. ADR 0012."
            )


def read_question(directory: Path) -> Question:
    text = (directory / "question.md").read_text()
    parsed = FRONT_MATTER.match(text)
    if parsed is None:
        raise QuestionError(f"{directory}: question.md has no front matter")
    front = yaml.safe_load(parsed.group(1))
    # The id becomes a file name and an environment variable, so it may not be empty, contain a
    # separator, or be anything a shell or a path would read as more than a name. An empty one
    # is the worst of them: it means "every question" to the page, so the record of what was
    # delivered for this question would quietly be a picture of all of them.
    identifier = str(front["id"])
    if not ID.match(identifier):
        raise QuestionError(
            f"{directory}: {identifier!r} is not a usable question id. It names a file and an "
            f"environment variable, so it must be lower-case letters, digits, hyphen and "
            f"underscore, and must not be empty."
        )
    return Question(
        directory=directory,
        id=identifier,
        status=Status(str(front["status"])),
        persona=str(front["persona"]),
        question=str(front["question"]),
        dimensions=tuple(str(d) for d in front["dimensions"]),
        defines=tuple(str(d) for d in front["defines"]),
        staged_sql=(directory / STAGED).read_text(),
        uss_sql=(directory / USS).read_text(),
        body=parsed.group(2),
    )


def read_questions(root: Path) -> tuple[Question, ...]:
    return tuple(
        read_question(directory)
        for directory in sorted(root.iterdir())
        if (directory / "question.md").is_file()
    )


def check_question(question: Question, defined: dict[str, str]) -> None:
    """Refuse a question that cannot be answered, or answered honestly."""
    for token in question.tokens:
        if token not in defined:
            raise QuestionError(
                f"{question.id}: {{{{{token}}}}} resolves to nothing. A question references "
                f"definitions and never restates one, so a token with no definition behind "
                f"it is a gap in the model -- fill it there first."
            )
    missing = [name for name in question.defines if name not in defined]
    if missing:
        raise QuestionError(f"{question.id}: declares {missing}, which nothing defines")

    control = without_comments(question.staged_sql).lower()
    for forbidden in ("dab.", "dab__", "dar__uss"):
        if forbidden in control:
            raise QuestionError(
                f"{question.id}: the control query mentions {forbidden!r}. It must compute "
                f"the answer independently, or agreement between the two proves nothing."
            )
    if "das__staged." not in control or "__current" not in control:
        raise QuestionError(
            f"{question.id}: the control query must read a das__staged __current view. "
            f"Reading the raw layer or the lake skips the contract's casts, which is what "
            f"makes agreement mean anything."
        )

    answer = without_comments(question.uss_sql).lower()
    parsed = _parsed(answer)
    if parsed.get("error"):
        raise QuestionError(
            f"{question.id}: the answer query does not parse -- "
            f"{parsed.get('error_message', 'the engine did not say why')}. Refused here rather "
            f"than at the next build, after a page has been written against it."
        )
    if "dar__uss" not in answer:
        raise QuestionError(f"{question.id}: the answer query does not read the star schema")
    for forbidden in ("das__", "dab.", "dab__", "read_parquet"):
        if forbidden in answer:
            raise QuestionError(
                f"{question.id}: the answer query mentions {forbidden!r}. A destination reads "
                f"the star schema and nothing else -- the page runs this query verbatim, so a "
                f"reach past it would render, pass, and be exactly the invisible dependency "
                f"the flow rules exist to prevent."
            )

    for body, side in ((control, "control"), (answer, "answer")):
        if "order by" not in body:
            raise QuestionError(
                f"{question.id}: the {side} query has no ORDER BY. The two answers are "
                f"compared row by row, so without one an identical pair can differ by the "
                f"order the engine happened to return, and someone goes looking for a data "
                f"bug that is not there."
            )

    # Only the answer query. The control expresses the same dimension in the source's own
    # words -- that difference is what makes it independent rather than a transcription.
    for dimension in question.dimensions:
        if dimension.rsplit(".", 1)[-1].lower() not in answer:
            raise QuestionError(
                f"{question.id}: declares the dimension {dimension!r}, which the answer query "
                f"does not mention. The front matter is what a reader trusts."
            )

    _refuse_an_aggregate_the_bridge_does_not_protect(question, parsed)
